"""empty message

Revision ID: 4809905765a2
Revises: 
Create Date: 2024-10-21 20:43:36.333705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4809905765a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('passwords', sa.String(length=128), nullable=False),
    sa.Column('house', sa.String(length=128), nullable=False),
    sa.Column('senator1', sa.String(length=128), nullable=False),
    sa.Column('senator2', sa.String(length=128), nullable=False),
    sa.Column('president', sa.String(length=128), nullable=False),
    sa.Column('vp', sa.String(length=128), nullable=False),
    sa.Column('governor', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('questionsAnswered', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Integer(), nullable=False),
    sa.Column('weights', sa.Text(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_correct'), ['correct'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_governor'), ['governor'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_house'), ['house'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_passwords'), ['passwords'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_president'), ['president'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_questionsAnswered'), ['questionsAnswered'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_senator1'), ['senator1'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_senator2'), ['senator2'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_vp'), ['vp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_weights'), ['weights'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_wrong'), ['wrong'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_wrong'))
        batch_op.drop_index(batch_op.f('ix_user_weights'))
        batch_op.drop_index(batch_op.f('ix_user_vp'))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_state'))
        batch_op.drop_index(batch_op.f('ix_user_senator2'))
        batch_op.drop_index(batch_op.f('ix_user_senator1'))
        batch_op.drop_index(batch_op.f('ix_user_questionsAnswered'))
        batch_op.drop_index(batch_op.f('ix_user_president'))
        batch_op.drop_index(batch_op.f('ix_user_passwords'))
        batch_op.drop_index(batch_op.f('ix_user_house'))
        batch_op.drop_index(batch_op.f('ix_user_governor'))
        batch_op.drop_index(batch_op.f('ix_user_correct'))

    op.drop_table('user')
    # ### end Alembic commands ###
